### ISSUE TITLE
Quiver pet not producing inf arrows

### ISSUE THREAD

**Issue by msavitz** [JoelZBub/organic-free-range-pack#52]
unless I'm using it incorrectly... I've used multiple bows with the same result... arrows in inventory get spent even with the quiver pet.

[9:33 AM] STBlade: let me give it a quick try and see if i can replicate it
[9:37 AM] STBlade: hmm yes i don't seem to get infinite arrows either
[9:38 AM] STBlade: would you mind reporting it to the dev team here

**Comment by msavitz** [comment]
allowed pet to nom on feathers and retried.  Same result.

**Comment by dommrogers** [comment]
### Describe the Bug:
Quiver pet from Inventory Pets doesn't give infinite arrows as the tooltip suggests.
Vanilla bow does not work.
Thermal foundation bow does not work.
Dragon scale bow **did** work.

### How Can We Reproduce the Bug:
1. Craft a vanilla bow and grab a stack of arrows
2. With the quiver pet in the hotbar and feathers in the inventory (ensure the pet is fed)
3. Shoot the bow, the arrows get consumed.

### Expected behavior:
The arrows stop being consumed as you continue to shoot the bow.

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : Tested with and without
 - Does this issue affect Server, Client, or Both? : Tested both single player and on server

**Comment by happybandit360** [comment]
https://github.com/capnkirok/Inventory-Pets/issues/332 - Incompatible with COFH

**Comment by happybandit360** [comment]
Due to this issue being beyond our control, we are disabling the Quiver pet, as other Infinity options are available.
